// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRfaNYIUyVAN8j4ej0oV6FrgASi2ErZM',
    appId: '1:520529142503:android:49fe028ea1041074727842',
    messagingSenderId: '520529142503',
    projectId: 'daily-coding-questions-app',
    storageBucket: 'daily-coding-questions-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5baOg_IKs0w0qSDv0NvPq9AKq9b36os',
    appId: '1:520529142503:ios:41fb1f41a871a6fb727842',
    messagingSenderId: '520529142503',
    projectId: 'daily-coding-questions-app',
    storageBucket: 'daily-coding-questions-app.firebasestorage.app',
    iosBundleId: 'com.example.dailyCodingQuestionsApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmqq7Yzf9QQsofwu8kYMByEujcsBgcon4',
    appId: '1:520529142503:web:b9d3703ba5e4b8d6727842',
    messagingSenderId: '520529142503',
    projectId: 'daily-coding-questions-app',
    authDomain: 'daily-coding-questions-app.firebaseapp.com',
    storageBucket: 'daily-coding-questions-app.firebasestorage.app',
    measurementId: 'G-5V0YSN1X5H',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5baOg_IKs0w0qSDv0NvPq9AKq9b36os',
    appId: '1:520529142503:ios:41fb1f41a871a6fb727842',
    messagingSenderId: '520529142503',
    projectId: 'daily-coding-questions-app',
    storageBucket: 'daily-coding-questions-app.firebasestorage.app',
    iosBundleId: 'com.example.dailyCodingQuestionsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmqq7Yzf9QQsofwu8kYMByEujcsBgcon4',
    appId: '1:520529142503:web:1251110b0d175647727842',
    messagingSenderId: '520529142503',
    projectId: 'daily-coding-questions-app',
    authDomain: 'daily-coding-questions-app.firebaseapp.com',
    storageBucket: 'daily-coding-questions-app.firebasestorage.app',
    measurementId: 'G-SRD7RG42E0',
  );

}